version: "3"
services:
  jellyfin:
    image: elgoog/xvideo
    container_name: xvideo
    ports:
      - 9080:80
    volumes:
      - /home/share/sdb/pornhub:/home/xvideo/download
      - /etc/localtime:/etc/localtime
    restart: unless-stopped
